# Generated by Django 5.1.3 on 2024-12-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='redes_sociales',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
