# Generated by Django 5.1.3 on 2024-12-06 04:26

import apps.administrador.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_negocio_redes_sociales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(default='logos/default_logo.png', upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'], message='Solo se permiten archivos JPG, JPEG y PNG.')]),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(help_text='El teléfono debe tener exactamente 10 dígitos.', max_length=10, validators=[apps.administrador.models.validate_telefono]),
        ),
    ]
