# Generated by Django 5.1.3 on 2024-12-17 20:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_negocio_logo_alter_negocio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default='logos/default_logo.png', help_text='Logo del negocio. Solo se permiten archivos JPG, JPEG y PNG.', max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
