# Generated by Django 5.1.3 on 2024-12-09 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='costo_alquiler',
            new_name='costo_total',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='fecha_alquiler',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='hora_inicio_reserva',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cantidad_unidades',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_hora_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
