# Generated by Django 5.1.3 on 2024-12-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_costo_alquiler_alquiler_costo_total_and_more'),
        ('servicios', '0002_delete_tiposervicio_servicio_imagen_referencial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='evento',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
