# Generated by Django 5.1.3 on 2024-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_alquiler_evento_alquiler_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
