# Generated by Django 5.1.3 on 2024-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alquiler_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='hora_fin_planificada',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_fin_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
