# Generated by Django 5.1.3 on 2024-12-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_alquiler_hora_fin_planificada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='hora_fin_planificada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
