# Generated by Django 5.1.3 on 2024-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alquiler_hora_fin_planificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='hora_fin_planificada',
            field=models.TimeField(),
        ),
    ]
