# Generated by Django 5.1.3 on 2024-12-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_alquiler_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='hora_fin_planificada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
