# Generated by Django 5.1.3 on 2024-12-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_alquiler_hora_fin_planificada'),
        ('servicios', '0002_delete_tiposervicio_servicio_imagen_referencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.combo'),
        ),
    ]
