# Generated by Django 5.1.3 on 2024-12-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'verbose_name': 'Tipo de Evento', 'verbose_name_plural': 'Tipos de Eventos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='numero_horas_permitidas',
            field=models.IntegerField(verbose_name='Número de Horas Permitidas'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoevento', verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor_extra_hora',
            field=models.FloatField(verbose_name='Valor Extra por Hora'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor_referencial',
            field=models.FloatField(verbose_name='Valor Referencial'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Evento'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='tipo_publico',
            field=models.CharField(max_length=50, verbose_name='Tipo de Público'),
        ),
    ]
