# Generated by Django 5.1.3 on 2024-12-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_megusta_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='visualizaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
