# Generated by Django 5.1.3 on 2024-12-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publicacion_visualizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
