# Generated by Django 5.1.3 on 2024-12-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_publicacion_fecha_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='me_gustas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MeGusta',
        ),
    ]
