# Generated by Django 5.1.3 on 2024-12-15 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_publicacion_me_gustas_delete_megusta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='me_gustas',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='me_gustas',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_likeadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
