# Generated by Django 5.1.3 on 2024-12-06 20:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('valor_por_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_servicio', models.CharField(choices=[('individual', 'Individual'), ('combo', 'Combo')], default='individual', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de servicio (único).', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.combo')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='servicios_incluidos',
            field=models.ManyToManyField(blank=True, related_name='combos', to='servicios.servicio'),
        ),
    ]
