# Generated by Django 5.1.3 on 2024-12-06 21:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_referencial',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen referencial del servicio', max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(help_text='Descripción del servicio ofrecido'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('individual', 'Individual'), ('combo', 'Combo')], default='individual', help_text='Especifica si el servicio es individual o parte de un combo', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(help_text='Título del servicio, ej. Alquiler de sillas', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_por_unidad',
            field=models.DecimalField(decimal_places=2, help_text='Valor por unidad del servicio', max_digits=10),
        ),
    ]
